name: Snyk for Gradle GitHub Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup JDK 17 for Gradle to support Snyk Action
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "adopt" # See 'Supported distributions' for available options

      # Setup Node.js as a prerequisite for Snyk CLI
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      # Install Gradle dependencies
      - name: Install Gradle dependencies
        run: ./gradlew build --no-daemon
    
      # List files in app directory
      - name: List files in app directory
        run: ls -la app

      # Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk
    
      # Check Snyk CLI version
      - name: Check Snyk CLI version
        run: snyk --version

      # Run Snyk on project
      - name: Run Snyk on project
        working-directory: app
        run: snyk test --file=build.gradle.kts --sarif --continue-on-error --debug > snyk_report.sarif 2> snyk_errors.log
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Output Snyk error logs
      - name: Output Snyk error logs
        run: cat app/snyk_errors.log

      # Output sarif report 
      - name: Output sarif report for debugging
        run: cat app/snyk_report.sarif
        
      # Upload sarif results to GitHub
      - name: Upload sarif results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: app/snyk_report.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

